CakePHP/Sniffs/Commenting/DocBlockAlignmentSniff.php
CakePHP/tests/files/docblock_align_fail.php
CakePHP/tests/files/docblock_align_pass.php
CakePHP/tests/files/short_open_tags_pass.php

Refs https://github.com/cakephp/cakephp/commit/78e9979177daccf8b8525e3bad01bbf35ea49fdc#commitcomment-9532176

Add DocBlockAlignmentSniff

---

README.md

Remove outdated phpunit note in README

---

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php
CakePHP/tests/CakePHPStandardTest.php
CakePHP/tests/files/function_comment_opening_line_fail.php
CakePHP/tests/files/function_comment_type_fail.php
CakePHP/tests/files/function_comment_type_pass.php
CakePHP/tests/files/function_comment_type_void_fail.php

Happy to rebase if you want to merge #134 first.

Fix return void when multiple return types specified

---

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php

Resolve issue with yield and @return

---

CakePHP/ruleset.xml

See https://github.com/cakephp/cakephp-codesniffer/issues/161

Relax PSR1.Files.SideEffects also for config/

---

CakePHP/Sniffs/NamingConventions/ValidFunctionNameSniff.php
CakePHP/Sniffs/NamingConventions/ValidTraitNameSniff.php
CakePHP/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
CakePHP/Tests/NamingConventions/ValidFunctionNameUnitTest.php

so check for Traits existance are useless.
Also start cleanup and improving code coverage

3.0 - minimum version is 5.4

---

CakePHP/Sniffs/NamingConventions/ValidFunctionNameSniff.php

Remove private method sniff

---

CakePHP/Sniffs/WhiteSpace/EmptyLinesSniff.php
CakePHP/tests/files/multiple_blank_lines_fail.php
CakePHP/tests/files/multiple_blank_lines_inside_class_fail.php

Check for multiple blank lines.

---

README.md

Running tests for this repo is a bit unconventional.

Add testing docs.

---

CakePHP/Sniffs/NamingConventions/UpperCaseConstantNameSniff.php
CakePHP/tests/files/return_type_declaration_pass.php

ConstantNotUpperCase avoid return type declarations #204

---

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php

Fix inheritdoc

---

CakePHP/Sniffs/WhiteSpace/EmptyLinesSniff.php
CakePHP/Tests/WhiteSpace/EmptyLinesUnitTest.inc
CakePHP/Tests/WhiteSpace/EmptyLinesUnitTest.php

Don't reach into non-existant indexes.
Fixes #221

Fix multiple blank line fixer.

---

CakePHP/ruleset.xml

- Cleaned up duplicate rules (probably caused by bad merge).
- Added couple of new rules.

Ruleset update

---

CakePHP/ruleset.xml
docs/README.md

Remove empty comments.

---

CakePHP/ruleset.xml

Now passes with https://github.com/cakephp/cakephp/pull/12993 merged.
I will adjust the dost post-merge. Avoids merge conflicts with other open PRs.

Add one line doc normalizer sniff.

---

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php
CakePHP/ruleset.xml

Now passes with https://github.com/cakephp/cakephp/pull/12994 merged.
I will adjust the dost post-merge. Avoids merge conflicts with other open PRs.

Add short list sniffer rule.

---

.travis.yml
composer.json

also better explicit coverage run.

Add prefer lowest check.

---

CakePHP/ruleset.xml

Refs https://github.com/cakephp/cakephp-codesniffer/issues/226
requires https://github.com/cakephp/cakephp/pull/13014 to be merged first.

Add SlevomatCodingStandard.Namespaces.UseSpacing

---

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php

Fixes https://github.com/cakephp/cakephp/pull/13279/checks?check_run_id=133901341

Fix CS for void detection.

---

README.md

Resolves https://github.com/cakephp/cakephp-codesniffer/issues/253

Add version map for clarity

---

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php
CakePHP/Sniffs/Formatting/BlankLineBeforeReturnSniff.php
CakePHP/Sniffs/WhiteSpace/EmptyLinesSniff.php
CakePHP/Sniffs/WhiteSpace/OperatorSpacingSniff.php
CakePHP/ruleset.xml
composer.json

this has been backported from current 4.x sniffer set ( https://github.com/cakephp/cakephp-codesniffer/pull/205/files )

Ignore file header noise

---

README.md
composer.json
phpcs.xml
phpcs.xml.dist

I added a phpcs.xml file, and a phpcs.xml.dist file that the user can copy to the base of their project.
I also updated the README to reflect these changes.

Adding a phpcs.xml file.

---

.travis.yml
CakePHP/Sniffs/Commenting/FunctionCommentSniff.php
CakePHP/Sniffs/ControlStructures/ControlStructuresSniff.php
CakePHP/Sniffs/ControlStructures/ElseIfDeclarationSniff.php
CakePHP/Sniffs/ControlStructures/WhileStructuresSniff.php
CakePHP/Sniffs/Functions/ClosureDeclarationSniff.php
CakePHP/Sniffs/WhiteSpace/FunctionCallSpacingSniff.php
CakePHP/Sniffs/WhiteSpace/FunctionClosingBraceSpaceSniff.php
CakePHP/Sniffs/WhiteSpace/FunctionOpeningBraceSpaceSniff.php
CakePHP/Sniffs/WhiteSpace/TabAndSpaceSniff.php
composer.json

Don't set DEFAULT when running CHECKS config.

Update .travis config

---

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php

Fix check for empty comment for @throws tag.

---

LICENSE

This allows Github to auto detect the license type.

Sync license with core repo.

---

composer.json

Fixes https://github.com/cakephp/cakephp-codesniffer/issues/297

Run only CakePHP unit tests

---

CakePHP/Sniffs/PHP/DisallowShortOpenTagSniff.php
CakePHP/Sniffs/PHP/SingleQuoteSniff.php
docs/README.md

We have been using this for the last 3 years without a single incident. So quite safe to use - without false positives or alike.
4.2.0 minor

Add SingleQuoteSniff

---

CakePHP/ruleset.xml

Ignore rules not applicable migrations files.

---

CakePHP/Sniffs/Commenting/TypeHintSniff.php

Add $this and self to sort list

---

.github/workflows/ci.yml

Don't use a now unstable image when we should be able to use a one-liner

Fix matcher setup

---

CakePHP/Sniffs/Commenting/TypeHintSniff.php

Closes https://github.com/cakephp/cakephp-codesniffer/issues/347
Cannot add test case because codesniffer doesn't support setting properties for tests.

Add option to skip legacy generics
