CakePHP/Sniffs/Commenting/DocBlockAlignmentSniff.php, CakePHP/tests/files/docblock_align_flat_pass.php
If a file doesn't contain a namespace, consider it a flat file, and relax the docblock indentation rules.
Refs: https://github.com/cakephp/cakephp-codesniffer/pull/119#issuecomment-73640822
=> Relax docblock indentation for flat files

README.md
Using a relative path only allows running phpcs from `vendor/bin/phpcs` and will error if you try running it from `bin/phpcs`, etc. Suggesting an absolute path will let users run phpcs from anywhere.
=> Update installed_paths to an absolute path

CakePHP/ruleset.xml, composer.json
as it's now natively proposed squizlabs/php_codesniffer
=> enforce short array usage

CakePHP/Sniffs/NamingConventions/ValidFunctionNameSniff.php, CakePHP/tests/files/class_underscore_prefix_pass.php, CakePHP/tests/files/operator_spacing_pass.php
This removes the underscore prefix requirement for protected and private methods. This will allow us to run the sniffer against new repos/plugins that have dropped this convention. Meanwhile, we can be conscious about any proposed underscore prefix changes in Cake core.
=> Remove underscore requirement for protected/private methods

CakePHP/Sniffs/NamingConventions/UpperCaseConstantNameSniff.php, CakePHP/tests/files/constant_names_pass.php
They are fine and don't need to be upper cased.
=> Ignore PHP 5.5 ::class constants.

CakePHP/Sniffs/Formatting/BlankLineBeforeReturnSniff.php
This correctly does what c0c04662d2543e2d2f0633013381eafb0ee7ea61 intended. I actually tested it on Crud plugin and it yielded correct results.
=> Fix fixer code in "BlankLineBeforeReturn" sniff.

.travis.yml, CakePHP/ruleset.xml, composer.json
I've pointed some more rules that needed to be relaxed since we are using Zend NamingConvention Sniff while running the CS against Cakephp core.
@ADmad I've added Composer scripts has discussed, I hope that this is it what you had in mind more or less.
=> Relax more rules and add Composer scripts

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php
Most of the times PhpStorms autocompletes the {@inhertidoc} with all small caps.
=> Ignore the inheritDoc tag using insensitive case

CakePHP/Sniffs/WhiteSpace/FunctionSpacingSniff.php, composer.json, phpunit.xml
PHP Codesniffer 3.2 release notes says that in order to test you should include their bootstrap, so this PR does that.
This allows to use new options like [Ignoring Parts of a File](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file). for example the namespace sniff in migrations, also could be in bake templates until cakephp/migrations#213 gets resolved
```php
<?php
// phpcs:disable PSR1.Classes.ClassDeclaration.MissingNamespace
use Migrations\AbstractMigration;
class CreatePosts extends AbstractMigration
{
// ....
}
```
=> Allow php codesniffer 3.2

CakePHP/Sniffs/WhiteSpace/OperatorSpacingSniff.php, CakePHP/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, CakePHP/Tests/WhiteSpace/OperatorSpacingUnitTest.php, CakePHP/Tests/WhiteSpace/OperatorSpacingunitTest.inc.fixed
PSR12 recommends `declare(strict_types=1)` not `declare(strict_types = 1)`
=> Don't add spaces around declare() arguments.

README.md, composer.json, docs/README.md, docs/generate.php
I would like to propose a more verbosely written list of the explained ruleset.
We can easily update it using `composer docs`, just as we do at [Spryker](https://github.com/spryker/code-sniffer/tree/master/docs).
It is super useful to communicate the current included list, as it lists also the inherited ones :)
=> Explain standard.

CakePHP/ruleset.xml
Doesn't make much sense having this rule when we end up silencing it https://github.com/cakephp/cakephp/blob/8baeda92fbccc426608a2d347ead7f5dfccb5af1/phpcs.xml.dist#L6.
In apps too having "todo"s isn't a bad thing IMO.
=> Remove rule for "todo" annotations.

CakePHP/Sniffs/Classes/ClassFileNameSniff.php, docs/README.md
Helps to resolve issues about multiple classes per file (https://github.com/cakephp/cakephp/pull/12950) and typos.
vendor/bin/phpcs --colors -p tests/ --sniffs=CakePHP.Classes.ClassFileName
=> Include class name sniff.

CakePHP/ruleset.xml
Refs https://github.com/cakephp/cakephp-codesniffer/issues/226
Useful to prevent https://github.com/cakephp/cakephp/pull/13000/files
=> Add SlevomatCodingStandard.Variables.DuplicateAssignmentToVariable

.travis.yml
We had some performance improvements done recently in Spryker
Our findings I also want to share with u.
Apparently, cs sniffer is > 4x faster without xdebug on.
23s => 10s for master branch since we dont have too many tests yet.
In larger code bases with even more sniffs this is quite noticeable:
- huge repo: 1470s => now only 319s (24 => 5 min!)
- medium repo: 118s => now only 26s (2 => 0.5min)
=> Speed up CS run by factor 4

CakePHP/ruleset.xml, docs/README.md
This checks for issues similar to the ones fixed in cakephp/cakephp#13151.
=> Add sniff for invalid inline phpDocs with @var.

CakePHP/Sniffs/Classes/ReturnTypeHintSniff.php
This is copied over from [Spryker](https://github.com/spryker/code-sniffer) where it already serves PHP7.1+ typehinting checking for many months now to help chainable work properly.
Refs https://github.com/cakephp/cakephp-codesniffer/issues/239
It cannot find everything, e.g. when "inheritdoc" is used (https://github.com/FriendsOfCake/bootstrap-ui/pull/273/files#diff-f78b0cf313e75baaee6fc88f3a81a8daR71)
but in those cases there is still PHPStan outlining the error, as shown also in this PR.
=> Add necessary sniff for chainable.

CakePHP/ruleset.xml
There are too many failures in core for this sniff.
=> Ignore missing description for "throws" again.

CakePHP/ruleset.xml
With this change existing code like
```php
declare(strict_types=1);
namespace Foo;
```
will become
```php
declare(strict_types=1);
namespace Foo;
```
and code like 
```php
declare(strict_types=1);
/**
* docbblock
*/
namespace Foo;
```
will become 
```php
declare(strict_types=1);
/**
* docbblock
*/
namespace Foo;
```
=> Ensure a blank line after declare() statement.

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Sniffs/WhiteSpace/FunctionSpacingSniff.php
Fixes https://github.com/cakephp/cakephp/pull/13223/files#diff-f615e67b9f687da027b935bbf938fd8eR281
needs to be merged into cake4 one then as well.
Resolves
```php
interface AnotherInterface
{
public function doSomethingElse();
/**
* @return void
*/
public function doSomethingX();
public function doSomethingY();
public function doSomethingZ();
}
```
to
```php
interface AnotherInterface
{
public function doSomethingElse();
/**
* @return void
*/
public function doSomethingX();
public function doSomethingY();
public function doSomethingZ();
}
```
etc
=> Fix: Interface method spacing

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php
This fixes a bug I ran in to:
PHP Fatal error: Uncaught exception 'PHP_CodeSniffer\Exceptions\RuntimeException' with message 'Undefined offset: 0 in .../phpcs-cake3/vendor/cakephp/cakephp-codesniffer/CakePHP/Sniffs/Commenting/FunctionCommentSniff.php on line 400' in .../phpcs-cake3/vendor/squizlabs/php_codesniffer/src/Runner.php:606
=> Fixing a zero offset bug

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php
Previously this would generate `Function return type is not void, but function has no return statement` error
```php
/**
* @return iterable
*/
public function fn()
{
yield from [1, 2, 3];
}
```
Should be handled same as `yield`
=> Fix function return type with `yield from`

CakePHP/ruleset.xml
PHP's type coercion is actually preferred in templates.
=> Don't enforce strict typing in template files.

CakePHP/ruleset.xml
Ignored PSR12 rules related to file header which cannot be autofixed.
=> Remove rules no longer required.

CakePHP/ruleset.xml
and fix indentation to 4 spaces.
Added
<rule ref="PSR12"/>
This then also needs to be merged over to 4.x one.
It basically adds
- PSR12.Classes.ClassInstantiation
- PSR12.Functions.NullableTypeDeclaration
- PSR12.Keywords.ShortFormTypeKeywords
- PSR12.Namespaces.CompoundNamespaceDepth
- PSR12.Operators.OperatorSpacing
I recommend not merging this before
is applied.
Then we can release a new minor, here 3.2.0
=> Add PSR12 ruleset

CakePHP/ruleset.xml
> Visibility must be declared on all constants if your project supports PHP 7.1 or later
warnings etc are not useful for cake3.x
=> Silence PHP7 only sniffs.

CakePHP/Sniffs/Formatting/UseInAlphabeticalOrderSniff.php, CakePHP/Tests/Formatting/UseInAlphabeticalOrderUnitTest.3.inc
fixes #214
That can enable work with PSR12.Files.FileHeader.IncorrectGrouping
=> Checked separately for ordering by `use function` and `use const`

CakePHP/Sniffs/Commenting/DocBlockAlignmentSniff.php, CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Sniffs/PHP/CommaAfterArrayItemSniff.php, CakePHP/Tests/Commenting/DocBlockAlignmentUnitTest.php
Backports the PHP7 and Cake4 trailing comma to PHP5 and Cake3 to keep the files in sync (less diff issues).
Also `@inheritDoc` should be properly detected as full overwrite.
=> Added trailing comma sniff and fixed inheritdoc detect

composer.json
This is mainly to include the fix for https://github.com/slevomat/coding-standard/issues/772 (Which directly affects our template files)
=> Upgrade to use slevomat/coding-standard v6

CakePHP/ruleset.xml
This check tries to assume things about the way static analyzers need type hints on variables which doesn't work.
=> Disabled NoAssignment error from inline docblocks

composer.json
why are we still setting that dependency manually in the first place? squizlabs/php_codesniffer
=> Fix min constraint

CakePHP/Sniffs/Commenting/InheritDocSniff.php, CakePHP/Tests/Commenting/InheritDocUnitTest.1.inc, CakePHP/Tests/Commenting/InheritDocUnitTest.php
This sniff only tests the `@inheritDoc` comment not `{@inheritDoc}`. This sniff adds 0 failures to current cakephp master branch.
=> Add sniff to test whether @inheritDoc is the only comment in doc block.

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Sniffs/Commenting/InheritDocSniff.php, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc.fixed, CakePHP/Tests/Commenting/InheritDocUnitTest.1.inc, CakePHP/Tests/Commenting/InheritDocUnitTest.1.inc.fixed, CakePHP/Tests/Commenting/InheritDocUnitTest.php
This enables function comment sniffs when the comment starts with `{@inheritDoc}` only instead of checking entire block for it.
=> Added sniffs checking that {@inheritdoc} is formatted correctly.

composer.json
Change can be reverted after slevomat/coding-standard#954 is addressed.
=> Clamp down Slevomat CS to <6.2.

README.md
If going to suggest modifying people's installed paths directly to install this standard, probably also worth suggesting [`dealerdirect/phpcodesniffer-composer-installer`](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) package which can do it all for you, and is decently widely recommended.
=> Suggest using composer package to handle phpcs installed_paths

CakePHP/Sniffs/Commenting/InheritDocSniff.php, CakePHP/Tests/Commenting/InheritDocUnitTest.1.inc, CakePHP/Tests/Commenting/InheritDocUnitTest.1.inc.fixed, CakePHP/Tests/Commenting/InheritDocUnitTest.php, composer.json
I accidentally broke setting the installed_paths for unit tests earlier.
Other doc comment sniffs throw warnings instead of errors so inheritDoc should do the same.
=> Changed inheritDoc errors to warnings and updated messages

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc.fixed, CakePHP/Tests/Commenting/FunctionCommentUnitTest.php
Closes https://github.com/cakephp/cakephp-codesniffer/issues/294
This makes it easier to override a function just to add some error handling or special static analyzer tags. These tags don't require validating the entire function/etc.
=> Allow {@inheritDoc} doc comments to include certain tags

composer.json
v6.3.6 contains a fix we need to avoid false positives for CakePHP codebase.
=> Bump up Slevomat CS version.

CakePHP/ruleset.xml
We disabled part of their analysis, this disables the rest. Slevomat doesn't need to validate how static analyzers use inline @var tags.
=> Disable slevomat evaluating inline @var comments

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc.fixed, CakePHP/Tests/Commenting/FunctionCommentUnitTest.php
Fixes https://github.com/cakephp/cakephp-codesniffer/issues/311
The important cases are already handled by SlevomatCodingStandard.TypeHints.LongTypeHints.UsedLongTypeHint
=> Removed InvalidReturn sniff as it doesn't handle compound types

composer.json
Can't run the test suite on PHP 8 as PHPCS's test suite hasn't been updated to support PHP8 / phpunit 9.
=> Allow using the sniffer on PHP 8.

CakePHP/ruleset.xml, docs/README.md
SlevomatCodingStandard.Classes.UnusedPrivateElements was marked as deprecated and finally was removed from the slevomat repository.
=> remove unexists rule

CakePHP/ruleset.xml
Since PSR12 extends and "replaces" PSR2, we shouldn't need to include it here. PSR12 standard includes the relevant PSR2 sniffs.
Removed anti-PSR12 rule suppressions since PSR12 already suppresses these rules:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR12/ruleset.xml#L232
=> Remove PSR2

CakePHP/ruleset.xml
This option defaults to true when using php 8+ which causes inconsistent results. Disabling by default to get the same results with 7.4 and 8.0.
=> Disable requiring $object::class

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Sniffs/WhiteSpace/FunctionSpacingSniff.php, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc.fixed, composer.json
This will prevent errors for code like:
```php
/**
* docblock
*/
#[ReturnTypeWillChange]
public function foo()
```
=> Allow attribute between docblock and function.

CakePHP/Sniffs/Classes/ReturnTypeHintSniff.php
The `ReturnTypeHintSniff` was not properly reporting its sniff codes on errors, making it (for me) to track down where this was even coming from. This is because the `addError` function from PHPCS expects either you pass it a string that represents the error code from this sniff file (which it constructs) or the fully quantified code when using `.`. This file was using the latter, but not actually providing the full quantification, which was then missing up `phpcs -e` as well as printing out a somewhat confusing error code for tracking down where itw was coming from. This fixes it so that now they're properly quantified, and match what was printed within the README for sniffs coming from this file (`CakePHP.Classes.ReturnTypeHint`).
Looking at the code, I was not sure if there was a …
=> Fix ReturnTypeHintSniff error codes missing CakePHP namespace

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc.fixed, CakePHP/Tests/Commenting/FunctionCommentUnitTest.php, CakePHP/ruleset.xml
This was tested against cakephp/cakephp.
The mixed and union specific options are disabled for now until we decide how to update types in cake 5. We don't want cs to fail every type that isn't a native type.
=> cake 5: Switch to slevomat parameter typehint sniffs

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc, CakePHP/Tests/Commenting/FunctionCommentUnitTest.inc.fixed, CakePHP/Tests/Commenting/FunctionCommentUnitTest.php
@ADmad This supports spacing in several variations between the docblock, attributes and function.
Cleaned up the old function processing code. This should reduce the amount of code we have to support.
The logic for finding the docblock end is based on slevomat.
=> cake 5: Extend doc comment and attribute spacing checks

CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Sniffs/Commenting/TypeHintSniff.php, CakePHP/Tests/Commenting/FunctionCommentUnitTest.php, CakePHP/Tests/Commenting/TypeHintUnitTest.1.inc, CakePHP/Tests/Commenting/TypeHintUnitTest.1.inc.fixed, CakePHP/Tests/Commenting/TypeHintUnitTest.php, CakePHP/ruleset.xml
Refs https://github.com/cakephp/cakephp/issues/15528
=> cake 5: Sort param and return type hints

CakePHP/Sniffs/Classes/ReturnTypeHintSniff.php, CakePHP/Sniffs/Commenting/DocBlockAlignmentSniff.php, CakePHP/Sniffs/Commenting/FunctionCommentSniff.php, CakePHP/Sniffs/Formatting/BlankLineBeforeReturnSniff.php, CakePHP/Sniffs/WhiteSpace/FunctionSpacingSniff.php, CakePHP/Tests/Classes/ReturnTypeHintUnitTest.inc, CakePHP/Tests/Classes/ReturnTypeHintUnitTest.php, CakePHP/Tests/Classes/ReturnTypeHintUnitTestinc.fixed
This avoid string comparisons and ensures we use correct values.
=> Convert use of token type to code

CakePHP/Sniffs/Commenting/TypeHintSniff.php, CakePHP/Tests/Commenting/TypeHintUnitTest.1.inc, CakePHP/Tests/Commenting/TypeHintUnitTest.1.inc.fixed
This handles single types as well now.
@ADmad
=> Convert array type to generic in non-unions

CakePHP/Sniffs/Commenting/TypeHintSniff.php, CakePHP/ruleset.xml
@ADmad This adds the property hint sniffs but disables missing native types like the parameter and return sniffs.
There are no errors in 4.next with this.
=> cake 5: Add slevomat property type hint sniffs

CakePHP/ruleset.xml
=> Add sniff to require use statements

CakePHP/Sniffs/Commenting/TypeHintSniff.php, CakePHP/Tests/Commenting/TypeHintUnitTest.1.inc, CakePHP/Tests/Commenting/TypeHintUnitTest.1.inc.fixed, CakePHP/Tests/Commenting/TypeHintUnitTest.php
Fixes https://github.com/cakephp/cakephp-codesniffer/issues/351
=> Remove parenthesis next to commas

.github/workflows/ci.yml, CakePHP/Sniffs/Commenting/TypeHintSniff.php, CakePHP/Tests/Commenting/TypeHintUnitTest.1.inc, CakePHP/Tests/Commenting/TypeHintUnitTest.1.inc.fixed, CakePHP/Tests/Commenting/TypeHintUnitTest.php
Reduce the number of tests and make them more specific. Easier to read than the random set of types.
=> Simplify test case for TypeHintSniff
